# -*- coding: utf-8 -*-
"""Aplicacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Y_QxUPMRfEHSzMZ2eNUNN88DjpSptl9

#Mi primera aplicación
"""

#Instalación de libreria
#!pip install streamlit

#Importación de librerias
import streamlit as st
import pandas as pd
import yfinance as yf

#Titulación
st.title("Mi primera aplicación en Streamlit")

#Lista de ticker inicial
lista_tickers = ["APL","MSFT","NVDA","META"]

#Multiselector
ticker = st.multiselect("Elija un ticker o varios",lista_tickers)

#Boton
if st.button("Descargar"):
  data=yf.download(ticker,period="1mo")["Close"]
  st.subheader("Precios de cierre")    
  st.dataframe(data)
