# -*- coding: utf-8 -*-
"""Aplicacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Y_QxUPMRfEHSzMZ2eNUNN88DjpSptl9

#Mi primera aplicación
"""

# Instalación de libreria
#!pip install streamlit

#Importación de librerias
import streamlit as st
import pandas as pd

st.title("Mi primera aplicación")
